/* ============================================
   DATOS DEL DIRECTORIO TURISTICO DE TUXPAN
   Datos reales investigados de fuentes publicas
   ============================================ */

const CATEGORIAS = [
    { id: "playas",        nombre: "Playas",              icono: "🏖️" },
    { id: "restaurantes",  nombre: "Restaurantes",        icono: "🍽️" },
    { id: "hoteles",       nombre: "Hoteles",             icono: "🏨" },
    { id: "historicos",    nombre: "Sitios Historicos",    icono: "🏛️" },
    { id: "actividades",   nombre: "Actividades",         icono: "🎯" },
    { id: "vida-nocturna", nombre: "Vida Nocturna",       icono: "🌙" },
    { id: "transporte",    nombre: "Transporte",          icono: "🚌" },
    { id: "servicios",     nombre: "Servicios Turisticos", icono: "📋" }
];

const ZONAS = {
    norte:  "Zona Norte",
    sur:    "Zona Sur",
    centro: "Centro",
    rio:    "Rio / Malecon",
    isla:   "Isla"
};

const LUGARES_DATA = [

    // ==================== PLAYAS ====================
    {
        id: "playa-norte",
        nombre: "Playa Norte",
        categoria: "playas",
        descripcion: "La playa mas extensa y popular de Tuxpan, con mas de 22 kilometros de arena dorada y aguas tranquilas ideales para nadar. Cuenta con palapas, restaurantes frente al mar, renta de sombrillas y actividades acuaticas. Es el destino principal para familias y para disfrutar de los espectaculares atardeceres del Golfo de Mexico.",
        descripcionCorta: "22 km de arena dorada con palapas, restaurantes y atardeceres.",
        direccion: "Boulevard Costero, Playa Norte, Tuxpan, Veracruz",
        zona: "norte",
        coordenadas: { lat: 20.9800, lng: -97.3300 },
        telefono: null,
        horario: "Acceso libre las 24 horas",
        precioRango: "gratis",
        calificacion: 4.5,
        numResenas: 328,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Estacionamiento", "Banos", "Palapas", "Restaurantes", "Deportes acuaticos"],
        etiquetas: ["familiar", "atardecer", "deportes acuaticos", "arena", "nadar"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "isla-lobos",
        nombre: "Arrecife Lobos-Tuxpan",
        categoria: "playas",
        descripcion: "Area Natural Protegida ubicada en el Golfo de Mexico, accesible desde Tamiahua en aproximadamente 1 hora en lancha. Ofrece aguas cristalinas con visibilidad de hasta 30 metros, perfectas para snorkel y buceo. Alberga arrecifes de coral con formaciones de mas de 200 anos, un faro historico y biodiversidad marina impresionante. Limite de 180 visitantes por dia. Mejor temporada: mayo a septiembre.",
        descripcionCorta: "Isla paradisiaca con arrecifes de coral, snorkel y faro historico.",
        direccion: "Isla de Lobos, acceso desde Tamiahua, Veracruz",
        zona: "isla",
        coordenadas: { lat: 21.4550, lng: -97.2280 },
        telefono: null,
        horario: "Tours diarios 7:00 - 15:00 (salidas desde Tamiahua)",
        precioRango: "$$",
        calificacion: 4.8,
        numResenas: 215,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Lanchas", "Guias certificados", "Snorkel", "Buceo", "Seguro"],
        etiquetas: ["naturaleza", "snorkel", "buceo", "isla", "aventura", "coral", "area protegida"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "playa-azul",
        nombre: "Playa Azul",
        categoria: "playas",
        descripcion: "Playa tranquila ubicada al sur de Tuxpan, conocida por sus aguas mas calmadas y su ambiente relajado. Menos concurrida que Playa Norte, es perfecta para quienes buscan un dia de playa sin multitudes.",
        descripcionCorta: "Playa tranquila y menos concurrida, ideal para relajarse.",
        direccion: "Playa Azul, Tuxpan, Veracruz",
        zona: "sur",
        coordenadas: { lat: 20.9280, lng: -97.3350 },
        telefono: null,
        horario: "Acceso libre las 24 horas",
        precioRango: "gratis",
        calificacion: 4.2,
        numResenas: 95,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Palapas", "Estacionamiento"],
        etiquetas: ["tranquila", "familiar", "relajante"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "barra-galindo",
        nombre: "Barra de Galindo",
        categoria: "playas",
        descripcion: "Playa al norte de Tuxpan donde el rio se encuentra con el mar. Destaca por avistamiento de delfines y acceso a buceo en arrecifes cercanos. Zona con conchas de colores y ambiente mas virgen que Playa Norte.",
        descripcionCorta: "Playa virgen con avistamiento de delfines y arrecifes cercanos.",
        direccion: "Barra de Galindo, 14.6 km al norte de Tuxpan",
        zona: "norte",
        coordenadas: { lat: 21.0904, lng: -97.3712 },
        telefono: null,
        horario: "Acceso libre",
        precioRango: "gratis",
        calificacion: 4.4,
        numResenas: 72,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Estacionamiento", "Buceo cercano"],
        etiquetas: ["virgen", "delfines", "naturaleza", "conchas"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },

    // ==================== RESTAURANTES ====================
    {
        id: "restaurante-malecon",
        nombre: "El Malecon Restaurante",
        categoria: "restaurantes",
        descripcion: "Restaurante tradicional con vista al rio Tuxpan. Especializado en mariscos frescos y cocina veracruzana. Sus platillos estrella incluyen el pulpo a las brasas, los camarones al coco y el ceviche estilo Tuxpan. Ambiente familiar con terraza.",
        descripcionCorta: "Mariscos frescos y cocina veracruzana con vista al rio.",
        direccion: "Malecon, Blvd. Jesus Reyes Heroles, Centro, Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9567, lng: -97.3960 },
        telefono: "+52 783 834 0001",
        horario: "Lunes a Domingo 10:00 - 22:00",
        precioRango: "$$",
        calificacion: 4.4,
        numResenas: 187,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Terraza", "Wi-Fi", "Estacionamiento", "Mariscos"],
        etiquetas: ["mariscos", "vista al rio", "familiar", "cocina veracruzana"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "la-playita-mariscos",
        nombre: "La Playita Mariscos",
        categoria: "restaurantes",
        descripcion: "Ubicado sobre Playa Norte, ofrece la experiencia completa: comer mariscos frescos con los pies en la arena y el sonido del mar. Famoso por su torre de mariscos y micheladas preparadas.",
        descripcionCorta: "Mariscos frescos frente al mar en Playa Norte.",
        direccion: "Playa Norte Km 3, Tuxpan, Veracruz",
        zona: "norte",
        coordenadas: { lat: 20.9700, lng: -97.3270 },
        telefono: "+52 783 837 0002",
        horario: "Martes a Domingo 11:00 - 20:00",
        precioRango: "$$",
        calificacion: 4.3,
        numResenas: 143,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Frente al mar", "Palapas", "Estacionamiento", "Mariscos"],
        etiquetas: ["mariscos", "playa", "frente al mar", "casual"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "cafe-tacita",
        nombre: "Tacita Cafe",
        categoria: "restaurantes",
        descripcion: "Acogedor cafe en el centro de Tuxpan. Ofrece cafe de especialidad, desayunos artesanales y reposteria casera. Un lugar perfecto para comenzar el dia o para una pausa por la tarde.",
        descripcionCorta: "Cafe de especialidad, desayunos y reposteria casera.",
        direccion: "Centro Historico, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9550, lng: -97.3980 },
        telefono: "+52 783 100 0003",
        horario: "Lunes a Sabado 8:00 - 21:00",
        precioRango: "$",
        calificacion: 4.6,
        numResenas: 98,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Wi-Fi", "Aire acondicionado", "Cafe de especialidad"],
        etiquetas: ["cafe", "desayunos", "reposteria", "acogedor"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "el-nuevo-veracruzano",
        nombre: "El Nuevo Veracruzano",
        categoria: "restaurantes",
        descripcion: "Considerado uno de los mejores restaurantes de mariscos en Tuxpan. Ofrece una amplia variedad que incluye mariscos, cocina mexicana, pizza y sushi. Algunas sucursales abren las 24 horas. Ideal para grupos grandes.",
        descripcionCorta: "El mejor de mariscos en Tuxpan, variedad de platillos.",
        direccion: "Blvd. Independencia 112, La Rivera, 92900 Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9555, lng: -97.3900 },
        telefono: null,
        horario: "Lunes a Domingo (algunas sucursales 24 hrs)",
        precioRango: "$$",
        calificacion: 3.9,
        numResenas: 245,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Estacionamiento", "Aire acondicionado", "Para llevar", "Grupos grandes"],
        etiquetas: ["mariscos", "mexicana", "sushi", "24 horas"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "mercado-municipal",
        nombre: "Mercado Municipal de Tuxpan",
        categoria: "restaurantes",
        descripcion: "El corazon gastronomico de Tuxpan. Aqui encuentras los sabores mas autenticos: bocoles con camaron, cueritos, cecina con enchiladas o estrujadas, y las bebidas locales Timbakey y Sony. Comida abundante y economica, ideal para probar la cocina regional.",
        descripcionCorta: "Comida tipica autentica: bocoles, cecina, cueritos y Timbakey.",
        direccion: "Centro, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9560, lng: -97.3985 },
        telefono: null,
        horario: "Lunes a Domingo 7:00 - 17:00",
        precioRango: "$",
        calificacion: 4.3,
        numResenas: 167,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Comida tipica", "Economico", "Antojitos"],
        etiquetas: ["mercado", "tipico", "bocoles", "cecina", "economico", "Timbakey"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },

    // ==================== HOTELES ====================
    {
        id: "hotel-tajin",
        nombre: "Hotel Tajin",
        categoria: "hoteles",
        descripcion: "Hotel clasico en el centro de Tuxpan con habitaciones comodas y bien equipadas. Ubicacion privilegiada cerca del malecon y de los principales puntos de interes. Ofrece alberca, restaurante y estacionamiento.",
        descripcionCorta: "Hotel centrico con alberca, restaurante y excelente ubicacion.",
        direccion: "Av. Juarez 44, Centro, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9560, lng: -97.3970 },
        telefono: "+52 783 834 0220",
        horario: "Recepcion 24 horas",
        precioRango: "$$",
        calificacion: 4.1,
        numResenas: 156,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Alberca", "Restaurante", "Estacionamiento", "Wi-Fi", "Aire acondicionado"],
        etiquetas: ["centrico", "alberca", "familiar", "negocios"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "hotel-playa-norte",
        nombre: "Hotel Playa & Sol",
        categoria: "hoteles",
        descripcion: "Hotel frente a Playa Norte con acceso directo a la playa. Habitaciones con vista al mar, alberca al aire libre y restaurante con mariscos.",
        descripcionCorta: "Hotel frente a Playa Norte con vista al mar y alberca.",
        direccion: "Blvd. Costero Km 5, Playa Norte, Tuxpan",
        zona: "norte",
        coordenadas: { lat: 20.9710, lng: -97.3260 },
        telefono: "+52 783 837 0100",
        horario: "Recepcion 24 horas",
        precioRango: "$$$",
        calificacion: 4.3,
        numResenas: 112,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Frente al mar", "Alberca", "Restaurante", "Estacionamiento", "Wi-Fi"],
        etiquetas: ["playa", "vista al mar", "lujo", "alberca"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "holiday-inn-tuxpan",
        nombre: "Holiday Inn Tuxpan",
        categoria: "hoteles",
        descripcion: "Hotel de cadena internacional con centro de convenciones. Ofrece alberca, gimnasio, estacionamiento gratuito. A 10 minutos de la playa y 5 del centro historico. Ideal para viajes de negocios y familias.",
        descripcionCorta: "Hotel de cadena con alberca, gimnasio y centro de convenciones.",
        direccion: "Blvd. La Calzada No. 33, Col. La Calzada, Tuxpan, Ver. 92773",
        zona: "centro",
        coordenadas: { lat: 20.9600, lng: -97.4050 },
        telefono: null,
        horario: "Recepcion 24 horas",
        precioRango: "$$$",
        calificacion: 4.2,
        numResenas: 198,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Alberca", "Gimnasio", "Estacionamiento gratis", "Wi-Fi", "Restaurante", "Centro de convenciones"],
        etiquetas: ["negocios", "cadena", "alberca", "gimnasio"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "isla-tajin-resort",
        nombre: "Isla Tajin Beach & River Resort",
        categoria: "hoteles",
        descripcion: "Resort premium ubicado donde el rio Tuxpan se encuentra con el Golfo de Mexico. Cuenta con spa completo, 2 albercas al aire libre, albercas privadas, restaurante gourmet y acceso directo a Playa Norte. La opcion mas lujosa de Tuxpan.",
        descripcionCorta: "Resort de lujo con spa, albercas y acceso a playa y rio.",
        direccion: "Km 4.5 Playa Norte a Barra Galindo, 92880 Tuxpan",
        zona: "norte",
        coordenadas: { lat: 20.9750, lng: -97.3280 },
        telefono: "+52 783 837 1611",
        horario: "Recepcion 24 horas",
        precioRango: "$$$",
        calificacion: 4.5,
        numResenas: 87,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Spa", "2 albercas", "Alberca privada", "Restaurante", "Playa", "Rio", "Wi-Fi"],
        etiquetas: ["lujo", "resort", "spa", "premium", "playa", "rio"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "courtyard-marriott",
        nombre: "Courtyard by Marriott Tuxpan",
        categoria: "hoteles",
        descripcion: "Hotel moderno con vista al rio Tuxpan. Alberca, centro de fitness, restaurante y a 5 minutos del centro historico. Excelente opcion para viajeros de negocios y turismo.",
        descripcionCorta: "Hotel moderno frente al rio con alberca y fitness center.",
        direccion: "Independencia 100-A, Col. La Rivera, 92870 Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9555, lng: -97.3950 },
        telefono: null,
        horario: "Recepcion 24 horas",
        precioRango: "$$$",
        calificacion: 4.3,
        numResenas: 134,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Alberca", "Fitness center", "Restaurante", "Wi-Fi", "Vista al rio"],
        etiquetas: ["moderno", "negocios", "rio", "marriott"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },

    // ==================== SITIOS HISTORICOS ====================
    {
        id: "museo-amistad",
        nombre: "Museo de la Amistad Mexico-Cuba",
        categoria: "historicos",
        descripcion: "Museo inaugurado el 4 de diciembre de 1988 que conmemora la estancia de Fidel Castro en Tuxpan antes de zarpar en el yate Granma hacia Cuba el 25 de noviembre de 1956. Cuenta con 3 salas permanentes (Fidel Castro, Jose Marti, El Cuate), 240.6 m2 de exhibicion con fotografias, uniformes, bustos y artefactos historicos. Ofrece visitas guiadas y tardes bohemias culturales.",
        descripcionCorta: "Museo historico sobre la partida del Granma hacia Cuba en 1956.",
        direccion: "Alvaro Obregon 1, Col. Santiago de la Pena, CP 92770, Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9486, lng: -97.4126 },
        telefono: "783 834 05 97",
        horario: "Martes a Sabado 10:00-18:00, Domingo 10:00-14:00. Lunes cerrado.",
        precioRango: "gratis",
        calificacion: 4.5,
        numResenas: 203,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Visitas guiadas", "Aire acondicionado", "Accesibilidad", "Tardes bohemias"],
        etiquetas: ["historia", "museo", "cultura", "cuba", "granma", "fidel"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "parque-reforma",
        nombre: "Parque Reforma",
        categoria: "historicos",
        descripcion: "El corazon de Tuxpan y centro de la vida social. Cuenta con una fuente danzante electronica con 240 salidas de agua que alcanzan hasta 20 metros de altura, con luces de 256 colores sincronizadas con musica (show a las 18:00 aprox.). Rodeado de edificios historicos, mas de 100 mesas bajo arboles podados en forma de cubo. Aqui se disfrutan bebidas locales como Timbakey y Sony, y noches de danzon.",
        descripcionCorta: "Parque central con fuente danzante de luces y 100+ mesas.",
        direccion: "Av. Benito Juarez, Centro, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9570, lng: -97.4000 },
        telefono: null,
        horario: "Acceso libre. Show de fuente ~18:00 hrs.",
        precioRango: "gratis",
        calificacion: 4.4,
        numResenas: 178,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Fuente danzante", "Mesas", "Area verde", "Kiosco", "Danzon"],
        etiquetas: ["parque", "centro", "paseo", "historico", "fuente", "danzon"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "catedral-tuxpan",
        nombre: "Catedral de Nuestra Senora de la Asuncion",
        categoria: "historicos",
        descripcion: "Construida en 1752, esta parroquia es una joya arquitectonica con detalles barrocos en su interior. Destaca por su construccion unica sin varillas ni hierro en su estructura interna. Ubicada frente al Parque Reforma, ha sido remodelada pero conserva una armoniosa mezcla de elementos antiguos y modernos.",
        descripcionCorta: "Templo de 1752 con arquitectura barroca, sin hierro en su estructura.",
        direccion: "Frente al Parque Reforma, Centro, Tuxpan",
        zona: "centro",
        coordenadas: { lat: 20.9562, lng: -97.3972 },
        telefono: null,
        horario: "Lunes a Domingo 7:00 - 20:00",
        precioRango: "gratis",
        calificacion: 4.4,
        numResenas: 89,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Accesibilidad"],
        etiquetas: ["iglesia", "colonial", "arquitectura", "centro", "1752", "barroco"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "castillo-teayo",
        nombre: "Zona Arqueologica Castillo de Teayo",
        categoria: "historicos",
        descripcion: "Piramide prehispanica de los siglos X-XII, unica por estar ubicada en el centro del pueblo moderno. Con 11.30 metros de altura, muestra influencias culturales huastecas y totonacas. Incluye museo de sitio con esculturas y piezas arqueologicas. Parte de la Ruta Huasteca Veracruzana, a 40 minutos de Tuxpan.",
        descripcionCorta: "Piramide prehispanica del siglo X en el centro del pueblo.",
        direccion: "Plaza de la Piramide s/n, Centro, Castillo de Teayo, Veracruz",
        zona: "sur",
        coordenadas: { lat: 20.7560, lng: -97.6320 },
        telefono: "746 882 00 48",
        horario: "Martes a Sabado 10:00-15:30",
        precioRango: "$",
        calificacion: 4.3,
        numResenas: 112,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Museo de sitio", "Guias", "Estacionamiento"],
        etiquetas: ["piramide", "arqueologia", "prehispanico", "huasteca", "totonaca", "ruta huasteca"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },

    // ==================== ACTIVIDADES ====================
    {
        id: "buceo-isla-lobos",
        nombre: "AQUALOREY Buceo Arrecifes Tuxpan",
        categoria: "actividades",
        descripcion: "Operador certificado de buceo recreativo en el Sistema Arrecifal Lobos-Tuxpan. Ofrece inmersiones para principiantes y experimentados en los arrecifes de coral del Golfo de Mexico. Incluye equipo completo, guias certificados y transporte en lancha.",
        descripcionCorta: "Buceo certificado en arrecifes de coral del Golfo de Mexico.",
        direccion: "Tuxpan, Veracruz",
        zona: "rio",
        coordenadas: { lat: 20.9530, lng: -97.3900 },
        telefono: null,
        horario: "Reservaciones previas, salidas 7:00 AM",
        precioRango: "$$",
        calificacion: 4.7,
        numResenas: 167,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Equipo incluido", "Guias certificados", "Transporte en lancha", "Seguro", "Principiantes"],
        etiquetas: ["buceo", "snorkel", "aventura", "naturaleza", "arrecife", "coral"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "pesca-deportiva",
        nombre: "Pesca Deportiva",
        categoria: "actividades",
        descripcion: "Tuxpan es destino de pesca deportiva de clase mundial. Se pescan marlin, dorado, atun y pez vela. Hay torneos la ultima semana de febrero y ultimo fin de semana de marzo. El Club de Pesca Farallon organiza competencias de peto, jurel y barracuda.",
        descripcionCorta: "Pesca de marlin, dorado y atun con embarcaciones equipadas.",
        direccion: "Puerto de Tuxpan, Veracruz",
        zona: "rio",
        coordenadas: { lat: 20.9530, lng: -97.3850 },
        telefono: "+52 783 834 0050",
        horario: "Salidas desde las 5:00 AM",
        precioRango: "$$$",
        calificacion: 4.6,
        numResenas: 78,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Embarcacion", "Equipo", "Guia", "Hielo y bebidas"],
        etiquetas: ["pesca", "mar", "aventura", "deportiva", "marlin", "torneo"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "paseo-lancha-negretti",
        nombre: "Paseos en Lancha Negretti",
        categoria: "actividades",
        descripcion: "Tours en lancha por el rio Tuxpan, manglares, estuarios de Tenechaco, Tumilco y Tampamachoco, y la laguna. Observacion de aves, cocodrilos y vida silvestre. Ubicado cerca del mercado principal.",
        descripcionCorta: "Tours por rio, manglares y estuarios con observacion de fauna.",
        direccion: "Cerca del Mercado Municipal, Malecon, Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9555, lng: -97.3940 },
        telefono: null,
        horario: "Diario 9:00 - 18:00",
        precioRango: "$",
        calificacion: 4.3,
        numResenas: 92,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Guia", "Chaleco salvavidas", "Tour narrado"],
        etiquetas: ["paseo", "rio", "naturaleza", "manglares", "aves", "cocodrilos"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "santuario-iguana",
        nombre: "Santuario de la Iguana",
        categoria: "actividades",
        descripcion: "Inaugurado en 2019 a lo largo del rio Tuxpan. Mas de 50 iguanas y garrobos viven en libertad en un area verde extensa. Se extiende desde el Parque de los Ninos Heroes hasta la Unidad Deportiva. Se recomienda llegar antes de las 16:00 cuando las iguanas se retiran a los arboles. Se permite alimentarlas con lechuga.",
        descripcionCorta: "Mas de 50 iguanas en libertad junto al rio Tuxpan.",
        direccion: "Calle Jose Adem Chahin, Col. Jardines de Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9580, lng: -97.4010 },
        telefono: null,
        horario: "Acceso libre. Mejor antes de 16:00 hrs.",
        precioRango: "gratis",
        calificacion: 4.2,
        numResenas: 88,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Acceso libre", "Area verde", "Mirador"],
        etiquetas: ["iguanas", "naturaleza", "rio", "animales", "gratis", "familia"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "laguna-tampamachoco",
        nombre: "Laguna de Tampamachoco y Manglares",
        categoria: "actividades",
        descripcion: "Laguna de aproximadamente 1,500 hectareas rodeada por 3,500 hectareas de manglares que alcanzan 8-15 metros de altura. Contiene los 4 tipos de mangle que existen en Mexico (rojo, negro, blanco y botoncillo). Tours en lancha por canales de manglar con observacion de aves, cocodrilos y vida silvestre.",
        descripcionCorta: "1,500 hectareas de laguna con los 4 tipos de mangle de Mexico.",
        direccion: "9 km al norte de Tuxpan, acceso por carretera costera",
        zona: "norte",
        coordenadas: { lat: 21.0000, lng: -97.3500 },
        telefono: null,
        horario: "Tours disponibles de 8:00 - 16:00",
        precioRango: "$",
        calificacion: 4.5,
        numResenas: 65,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Tours en lancha", "Observacion de aves", "Guia", "Fotografia"],
        etiquetas: ["laguna", "manglares", "naturaleza", "aves", "ecoturismo", "lancha"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "huerto-bambu",
        nombre: "El Huerto del Bambu",
        categoria: "actividades",
        descripcion: "Parque ecoturistico a orillas del rio Tuxpan. Ofrece kayak, pesca, natacion, temazcal (bano de vapor prehispanico), camping, rapel en arboles, tirolesa y talleres de bambu, pan artesanal, composta y sensorama. Cuenta con terrazas, palapas, areas infantiles y cabanas para pernoctar.",
        descripcionCorta: "Ecoturismo con kayak, temazcal, tirolesa y camping junto al rio.",
        direccion: "Camino a Ejido Juana Moza, junto al Rio Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9500, lng: -97.4100 },
        telefono: null,
        horario: "Viernes a Domingo y festivos 9:00-18:30",
        precioRango: "$",
        calificacion: 4.4,
        numResenas: 56,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Kayak", "Temazcal", "Tirolesa", "Camping", "Cabanas", "Talleres", "Area infantil"],
        etiquetas: ["ecoturismo", "kayak", "temazcal", "camping", "aventura", "bambu", "familia"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: true
    },
    {
        id: "tuxpan-adventures",
        nombre: "Tuxpan Adventures",
        categoria: "actividades",
        descripcion: "Empresa de turismo de aventura que ofrece recorridos en vehiculos RZR por la selva y caminos rurales, cabalgatas y excursiones de buceo/snorkel en los arrecifes de Tuxpan. Experiencias de adrenalina para todos los niveles.",
        descripcionCorta: "Aventuras en RZR por la selva, cabalgatas y buceo.",
        direccion: "Tuxpan, Veracruz (punto de reunion variable)",
        zona: "norte",
        coordenadas: { lat: 20.9700, lng: -97.3350 },
        telefono: null,
        horario: "Reservaciones previas",
        precioRango: "$$",
        calificacion: 4.5,
        numResenas: 43,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["RZR", "Cabalgata", "Buceo", "Equipo incluido", "Guia"],
        etiquetas: ["aventura", "rzr", "cabalgata", "adrenalina", "selva"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },

    // ==================== VIDA NOCTURNA ====================
    {
        id: "malecon-nocturno",
        nombre: "Malecon de Tuxpan",
        categoria: "vida-nocturna",
        descripcion: "El malecon se transforma por las noches en un paseo iluminado con puestos de comida, musica en vivo y ambiente festivo. Las Letras de Tuxpan son parada obligatoria para fotos. Los fines de semana es especialmente concurrido.",
        descripcionCorta: "Paseo nocturno con comida, musica y las Letras de Tuxpan.",
        direccion: "Blvd. Jesus Reyes Heroles, Malecon, Tuxpan",
        zona: "rio",
        coordenadas: { lat: 20.9565, lng: -97.3955 },
        telefono: null,
        horario: "Viernes a Domingo desde las 19:00",
        precioRango: "$",
        calificacion: 4.1,
        numResenas: 134,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Comida", "Musica en vivo", "Paseo", "Letras de Tuxpan"],
        etiquetas: ["malecon", "noche", "musica", "comida", "paseo", "fotos"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "bar-la-barra",
        nombre: "La Barra Sports Bar",
        categoria: "vida-nocturna",
        descripcion: "Bar deportivo popular entre locales y visitantes. Pantallas gigantes para ver partidos, buena seleccion de cervezas nacionales y cocteles. Ambiente relajado entre semana y animado los fines de semana.",
        descripcionCorta: "Bar deportivo con pantallas, cervezas y buen ambiente.",
        direccion: "Av. Benito Juarez, Centro, Tuxpan",
        zona: "centro",
        coordenadas: { lat: 20.9545, lng: -97.3965 },
        telefono: "+52 783 100 0020",
        horario: "Lunes a Sabado 17:00 - 02:00",
        precioRango: "$$",
        calificacion: 4.0,
        numResenas: 67,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Pantallas", "Cocteles", "Botanas", "Musica"],
        etiquetas: ["bar", "deportes", "cervezas", "noche"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },

    // ==================== TRANSPORTE ====================
    {
        id: "terminal-autobuses",
        nombre: "Terminal de Autobuses ADO",
        categoria: "transporte",
        descripcion: "Terminal principal con conexiones directas a Ciudad de Mexico (5 hrs), Veracruz, Tampico, Poza Rica y otras ciudades. Lineas ADO, AU y regionales. Sala de espera, sanitarios, cafeteria y servicio de taxi.",
        descripcionCorta: "Terminal principal ADO con rutas a CDMX, Veracruz y mas.",
        direccion: "Blvd. Reyes Heroles, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9540, lng: -97.4020 },
        telefono: "+52 783 834 0233",
        horario: "24 horas",
        precioRango: "$",
        calificacion: 3.8,
        numResenas: 210,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Sala de espera", "Sanitarios", "Taxis", "Cafeteria"],
        etiquetas: ["autobus", "transporte", "ado", "viaje", "cdmx"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "lanchas-isla",
        nombre: "Embarcadero de Lanchas",
        categoria: "transporte",
        descripcion: "Punto de salida de lanchas para tours por el rio, manglares, estuarios y la Laguna de Tampamachoco. Tambien se organizan salidas hacia Isla de Lobos (aunque el acceso principal es desde Tamiahua). Se recomienda llegar temprano en temporada alta.",
        descripcionCorta: "Lanchas para tours por rio, manglares y estuarios.",
        direccion: "Embarcadero, Malecon, Tuxpan, Veracruz",
        zona: "rio",
        coordenadas: { lat: 20.9520, lng: -97.3870 },
        telefono: null,
        horario: "Diario 7:00 - 16:00",
        precioRango: "$",
        calificacion: 4.0,
        numResenas: 145,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Lanchas", "Chalecos", "Guias disponibles"],
        etiquetas: ["lancha", "rio", "transporte", "embarcadero", "manglares"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },

    // ==================== SERVICIOS TURISTICOS ====================
    {
        id: "oficina-turismo",
        nombre: "Oficina de Turismo Municipal",
        categoria: "servicios",
        descripcion: "Oficina de informacion turistica del municipio de Tuxpan. Mapas, folletos, informacion sobre eventos y recomendaciones. Personal bilingue disponible. Punto de partida recomendado para planificar tu visita.",
        descripcionCorta: "Informacion turistica oficial con mapas y asesoria bilingue.",
        direccion: "Palacio Municipal, Centro, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9560, lng: -97.3978 },
        telefono: "+52 783 834 0100",
        horario: "Lunes a Viernes 9:00 - 17:00",
        precioRango: "gratis",
        calificacion: 4.0,
        numResenas: 45,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Informacion", "Mapas", "Folletos", "Personal bilingue"],
        etiquetas: ["informacion", "turismo", "mapas", "asesoria"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    },
    {
        id: "renta-autos",
        nombre: "Renta de Autos Tuxpan",
        categoria: "servicios",
        descripcion: "Servicio de renta de vehiculos para explorar Tuxpan y alrededores a tu propio ritmo. Desde compactos hasta SUVs. Incluye seguro basico y asistencia en carretera. Entrega en hotel disponible.",
        descripcionCorta: "Alquiler de vehiculos con seguro y entrega en hotel.",
        direccion: "Centro, Tuxpan, Veracruz",
        zona: "centro",
        coordenadas: { lat: 20.9548, lng: -97.3990 },
        telefono: "+52 783 100 0040",
        horario: "Lunes a Sabado 8:00 - 19:00",
        precioRango: "$$",
        calificacion: 3.9,
        numResenas: 34,
        imagenes: [],
        imagenPrincipal: null,
        servicios: ["Seguro incluido", "Asistencia vial", "Entrega en hotel"],
        etiquetas: ["renta", "auto", "vehiculo", "transporte"],
        sitioWeb: null,
        redesSociales: { facebook: null, instagram: null },
        destacado: false
    }
];
